# Compiler
CC = mpic++

# Compiler flags
CFLAGS = -std=c++11 -fopenmp

# MPI flags, adjust paths as found
MPI_FLAGS = -I/opt/homebrew/opt/open-mpi/include -L/opt/homebrew/opt/open-mpi/lib -lmpi

# Targets
all: trapez_omp

# Compile the executable
trapez_omp: trapez_omp.cpp
	$(CC) $(CFLAGS) $(MPI_FLAGS) -o trapez_omp trapez_omp.cpp

# Clean up
clean:
	rm -f trapez_omp
